name: "Brakeman static analysis"
description: "A GitHub Action that performs static analysis of your Ruby code with Brakeman."
author: Tan Nguyen, forked by Ben Dilley
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-square"
  color: "red"
